// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPbUpSqs7QFFOR14e3eGTqEQibzigVS8',
    appId: '1:138740288252:android:bb1e8f5c0812720e632579',
    messagingSenderId: '138740288252',
    projectId: 'symbolic-cinema-342401',
    storageBucket: 'symbolic-cinema-342401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFpr_rOnnxDfjJot4r-v8JpmJmavs7eQ',
    appId: '1:138740288252:ios:3e453c92cf770760632579',
    messagingSenderId: '138740288252',
    projectId: 'symbolic-cinema-342401',
    storageBucket: 'symbolic-cinema-342401.appspot.com',
    androidClientId: '138740288252-5s6c7jb6bv0p4rutsr43hs8f4n1kl61m.apps.googleusercontent.com',
    iosClientId: '138740288252-8i0qjdp086mmi7re4eleffp6fu8796ou.apps.googleusercontent.com',
    iosBundleId: 'com.leonel.teslamate',
  );
}
